version: "3"
services:
  quay:
    image: "registry:2.8"
    container_name: "quay"
    restart: "always"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./data:/var/lib/registry"
      - "./config.yml:/etc/docker/registry/config.yml"
    ports:
      - "127.0.0.1:5002:5000"
